site_name: PAN-OS MCP Server
site_description: Documentation for the PAN-OS Model Context Protocol Server
site_url: https://cdot65.github.io/pan-os-mcp
site_author: Calvin Remsburg
copyright: Copyright &copy; 2025 Palo Alto Networks

repo_name: cdot65/pan-os-mcp
repo_url: https://github.com/cdot65/pan-os-mcp
edit_uri: edit/main/docs/

theme:
  name: material
  logo: images/logo.svg
  favicon: images/logo.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Architecture: architecture.md
  - API Reference: api.md
  - Improvements: improvements.md

# Explicitly set the layout for home page with customizations
not_in_nav: |
  index.md
  STYLE_GUIDE.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list

extra_css:
  - css/termynal.css
  - css/custom.css

extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js
  - js/mermaid-init.js
  - js/termynal.js
  - js/custom_termynal.js

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
          selection:
            docstring_style: google
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      enable_git_follow: false
      fallback_to_build_date: true
