apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: panos-mcp-service-security-headers
  namespace: panos-mcp-service
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
    customFrameOptionsValue: "SAMEORIGIN"
