apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cors
  namespace: panos
spec:
  headers:
    accessControlAllowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    accessControlAllowOriginList:
      - "*"  # Consider restricting this in production
    accessControlAllowCredentials: true
    accessControlAllowHeaders:
      - "*"
    accessControlMaxAge: 100
