name: Code Quality

on:
  pull_request:
    branches: ["main", "swap-back-to-python"]
  workflow_dispatch:

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Run isort check
        run: |
          poetry run isort --check-only --profile black src tests

      - name: Run ruff lint
        run: |
          poetry run ruff check src tests

      - name: Run ruff format check
        run: |
          poetry run ruff format --check src tests

      - name: Run flake8
        run: |
          poetry run flake8 src tests

      - name: Run mypy type checking
        run: |
          poetry run mypy src

      - name: Run pyright type checking
        run: |
          poetry run pyright src
